services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - app-network
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - .:/srv/node/app
    environment:
      - NODE_ENV=development

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    networks:
      - app-network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./static:/usr/share/nginx/static:ro
      - ./html:/usr/share/nginx/html:ro
    depends_on:
      - app

networks:
  app-network:
    driver: bridge